name: script_hub
channels:
  - fenglab
  - defaults
dependencies:
  - python=3.10
  - pip
  - zimg
  - loguru
  - typer
  - celery
  - pip:
      - tensorstore
      - pydantic==2.*
      - deprecation
      - fastapi
      - uvicorn
      - neuroglancer_scripts
